### ISSUE TITLE
How to install without docker? As a python service ? Windows is not supported?

### ISSUE THREAD

**Issue by leslyarun** [bloomsburyai/cape-webservices#2]
Hi,
Can you please provide the steps to use it without Docker. I think Windows is not supported, because sanic is not supporting Windows. Correct me if I'm wrong.

**Comment by luisulloa** [comment]
Hello @leslyarun ,
Yes sanic pypi apparently does not currently work on windows, in that case you can :

- Install docker on windows, more info [here](https://docs.docker.com/docker-for-windows/)
- Try to install sanic on windows (not an expert on windows, sorry I cannot be more help), more info [here](https://github.com/channelcat/sanic/issues/855) 
- Use directly the library from your app or server: `pip3 install -vv --process-dependency-links --upgrade git+https://github.com/bloomsburyai/cape-responder`

Maybe the steps we follow for linux in the Dockerfile [here](https://github.com/bloomsburyai/cape-webservices/blob/master/deployment/Dockerfile) can be useful ?
Hope this helps,

**Comment by leslyarun** [comment]
@luisulloa After I perform `pip install -vv --process-dependency-links --upgrade git+https://github.com/bloomsburyai/cape-responder` in Linux, I still can't import  `from cape_responder.responder_core import Responder`. It says cape_responder not found
